name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: test
    #   run: |
    #     REPO="https://$GITHUB_ACTOR:$TOKEN@github.com/$GITHUB_REPOSITORY.git"
    #     echo $REPO

    - name: Get new version
      id: version
      run: |
        echo "{new_version}={$(./bumb_patch.sh)}" >> $GITHUB_OUTPUT

    - name: Bump new version
      run: |
        REPO="https://$GITHUB_ACTOR:$TOKEN@github.com/$GITHUB_REPOSITORY.git"
        mvn -q versions:set -DnewVersion="${{steps.version.outputs.new_version}}"
        git add ./pom.xml
        git commit -m "Bump pom.xml to version ${{steps.version.outputs.new_version}}"
        git tag ${{steps.version.outputs.new_version}}
        git push --follow-tags
        git push --tags

    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: ${{ steps.version.outputs.new_version }}
    #     release_name: Release ${{ steps.version.outputs.new_version }}
    #     body: Release ${{ steps.version.outputs.new_version }}
