name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Increment patch version
      id: version
      run: |
        echo "{new_version}={$(./bumb_patch.sh)}" >> $GITHUB_OUTPUT
        mvn -q versions:set -DnewVersion="${steps.version.outputs.new_version}"
        

    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: ${{ steps.version.outputs.new_version }}
    #     release_name: Release ${{ steps.version.outputs.new_version }}
    #     body: Release ${{ steps.version.outputs.new_version }}
