name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: test
    #   run: |
    #     echo ${{secrets.GIT_USER_EMAIL}}

    - name: Get new version
      id: version
      run: |
        echo "{new_version}={$(./bumb_patch.sh)}" >> $GITHUB_OUTPUT

    - name: Bump new version
      run: |
        REPO="https://$GITHUB_ACTOR:$TOKEN@github.com/$GITHUB_REPOSITORY.git"
        mvn -q versions:set -DnewVersion="${{steps.version.outputs.new_version}}"
    
    - name: Create release commit
      run: |
        git config --global user.email "<>"
        git config --global user.name "${{github.actor}}"
        git add ./pom.xml
        git commit -m "Release ${{steps.version.outputs.new_version}}"
        git tag ${{steps.version.outputs.new_version}}
        git push --follow-tags
        git push --tags