name: Maven on Docker CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  maven-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get new version
      id: version
      run: echo "new_version=$(./bump_patch.sh)" >> $GITHUB_OUTPUT

    - name: Set image name
      id: image_name
      run: echo "image_name=ghcr.io/danielbarda97/$(mvn help:evaluate -Dexpression=project.name -q -DforceStdout):${{steps.version.outputs.new_version}}" >> $GITHUB_OUTPUT

    - name: Bump new version
      run: |
        REPO="https://$GITHUB_ACTOR:$TOKEN@github.com/$GITHUB_REPOSITORY.git"
        mvn -q versions:set -DnewVersion="${{steps.version.outputs.new_version}}"

    - name: Run tests
      run: docker build --target tests -t test-image .

    - name: Build production image
      run: docker build --target builder -t ${{steps.image_name.outputs.image_name}} .

    - name: Publish docker-image to GHCR
      run: |
        docker login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
        docker push ${{steps.image_name.outputs.image_name}}

    - name: Make release tag & commit
      run: |
        git config --global user.email "<>"
        git config --global user.name "${{github.actor}}"
        git add ./pom.xml
        git commit -m "Release ${{steps.version.outputs.new_version}}"
        git tag ${{steps.version.outputs.new_version}}
        git push --follow-tags
        git push --tags

    - name: Deployment
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker kill $(docker ps -aq) &>/dev/null || true
          sudo docker rm $(docker ps -aq) &>/dev/null || true
          sudo docker rmi $(docker images -q)
          sudo docker pull ${{steps.image_name.outputs.image_name}}
          sudo docker run -d --name my-app ${{steps.image_name.outputs.image_name}}

    - name: Docker Logout
      run: docker logout ghcr.io || true
