name: Maven on Docker CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  maven-docker:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get new version
      id: version
      run: echo "new_version=$(./bump_patch.sh)" >> $GITHUB_OUTPUT

    - name: Set image name
      id: image_name
      run: echo "image_name=ghcr.io/danielbarda97/$(mvn help:evaluate -Dexpression=project.name -q -DforceStdout):${{ steps.version.outputs.new_version }}" >> $GITHUB_OUTPUT

    - name: Bump new version
      run: |
        REPO="https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
        mvn -q versions:set -DnewVersion="${{ steps.version.outputs.new_version }}"

    - name: Run tests
      run: docker build --target tests -t test-image .

    - name: Build production image
      run: docker build --target production -t ${{ steps.image_name.outputs.image_name }} .

    - name: Publish docker-image to GHCR
      run: |
        docker login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
        docker push ${{ steps.image_name.outputs.image_name }}

    - name: Make release tag & commit
      run: |
        git config --global user.email "<>"
        git config --global user.name "${{github.actor}}"
        git add ./pom.xml
        git commit -m "Release ${{ steps.version.outputs.new_version }}"
        git tag ${{ steps.version.outputs.new_version }}
        git push --follow-tags

    - name: Deployment
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ vars.EC2_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker kill $(docker ps -aq) &>/dev/null || true
          sudo docker system prune -af
          sudo docker pull ${{ steps.image_name.outputs.image_name }}
          sudo docker run -d --name my-app ${{ steps.image_name.outputs.image_name }}

    - name: Docker Logout
      if: always()
      run: docker logout ghcr.io || true
